### ISSUE TITLE
Self-contradicting comment in init.lua: Better to omit or to have partial pyramids?

### ISSUE THREAD

**Issue by mk-pmb** [ronoaldo/tsm_pyramids#1]
The comment in the `minetest.register_on_generated` callback in `init.lua` seems to contradict itself:

https://github.com/ronoaldo/tsm_pyramids/blob/d4d89c5cc4c4bcb02eae3436454632b2ad185ddf/init.lua#L325-L329

> --[[ Make sure the pyramid doesn't bleed outside of maxp,
> so it doesn't get placed incompletely by the mapgen.

Sounds like it's better to __omit__ the entire Pyramid if some parts would be missing.

> […] But it's still better to have broken pyramids.

Literally says it's better to __have__ them. Maybe a "than" is missing?

Also

> -- TODO: Use Minetests pseudo-random tools

Best would be to fix the TODO, 2nd best would be to add the apostrophe for "Minetest's".

**Comment by mckaygerhard** [comment]
repo is now at: https://codeberg.org/Wuzzy/minetest_tsm_pyramids/issues/2

i guess maybe this is a try to raise a piramid based on limits of the engine bug

**Comment by mckaygerhard** [comment]
i guess there's more here @mk-pmb i put this comment in new upstream author repo:

...  cos must not be called until after the world is finished initializing, there are not so much mods that use it but those mods does not raised an error do  you know?

this must be called as product of specific event after making some noiseperling as the source code said, seems mineitest developer are crap ones, cos documentation on lua api does not have any notes...

 calling at the top level mod initialization code maybe is the culprit? also seem it needs a kind of constructor initialization (missing documentation again?)

**Comment by mckaygerhard** [comment]
i have some piramits tunning the parametesr of the "speudo constructor" at line 241 of init.lua

ORIGINAL: https://codeberg.org/Wuzzy/minetest_tsm_pyramids/src/commit/408e33b76f51bf68bacf8b9e9f7268de264978c2/init.lua#L240

CULPRIT: https://github.com/ronoaldo/tsm_pyramids/blob/d4d89c5cc4c4bcb02eae3436454632b2ad185ddf/init.lua#L243

as i said: this must be called as product of specific event after making some kind of constructor initialization (missing documentation again?) that for me is the line 241 (+/- 3 lines) cited, as the source code said, seems mineitest developer are crap ones, cos documentation on lua api does not have any notes...

i tuned a bit and used mapgen v7 and as the picture shows get working piramits but using minetest 0.4.17 so i guess should add a workaround based on mapgen type

![screenshot_20230812_171643](https://github.com/ronoaldo/tsm_pyramids/assets/1571724/3be5e291-5c8d-4869-bdd9-41f2f2106c92)

**Comment by ronoaldo** [comment]
Hello! Thank you for the report but this is a fork of the upstream project that I made in order to have stable releases and apply small fixes/patches for my server. Kindly look up for the upstream at https://codeberg.org/Wuzzy/minetest_tsm_pyramids

Best regards,

**Comment by mckaygerhard** [comment]
@ronoaldo  seems author does not have interest in the patch.. and i send to us the solution in my thinking.. 

seems the constructor (line 241) has lack of parameters or maybe need to be in sync with desert biomes from mapgen parameters noises

**Comment by mckaygerhard** [comment]
> @mckaygerhard
> > seems mineitest developer are crap ones 
> I'm concerned about your attitude. There are so many well-tempered explanations for why some of the docs are less than ideal, that happen to also be way more plausible.

we can understand that making documentation it takes time, its a time consuming task and also its pretty slow task and demans so much dedication .. but unfortunatelly there are now more than 8 years since that line in api of lua in minetest was posted..  

> 
> > seems author does not have interest in the patch..
> Your wording may have had an influence on his motivation.

this demostrates @mk-pmb  that you dont read the upstream issue, author only accept patches but only for 5.7, also  there are some important things that author does not know:

- 90% of players and clients are cheaters
- 90% of players does not use 5.7, only multicraft
- 90% of the players still prefers some 0.4.17 servers as JT3 and subnasa
- 90% of players are mobile players

most of those facts are not of knowledge of author of the mod, supported by several benchmarks and stats in minetst forums.. and i just guess the common response to those: !in only do for me, i do in my free time, i do for original minetest" etc etc

i provide all the notes and read the doucmentations, i work the weekend into this and could not find a working solution

original mod its pretty working now with some patches that i will make public.. but was time consuming.. its so so angry that minetest developers just focus so much in "evolution developing" event "fixeds"..

i do what i can for provide hints to this problem, in comment: https://codeberg.org/Wuzzy/minetest_tsm_pyramids/issues/2#issuecomment-1040640

the older mod does not crash, as i said: based on mod guide https://minetest.gitlab.io/minetest/class-reference/#perlinnoise  inclusivelly having this issue https://github.com/minetest/minetest/issues/10385 because of that:**

> It can be created via PerlinNoise() or minetest.get_perlin(). **For minetest.get_perlin(), the actual seed used is the noiseparams seed plus the world seed**, to create world-specific noise.

seems the seed you use are not in sync with wold also based on the minetest code, unless `PerlinNoise()` the  minetest.get_perlin() only van be called in context and suggested onli called one time per mod, and only in init.lua file and after all the context its loaded, a better option is using `PerlinNoise()`, the documentation for this are so so vage for that and i was empty of time with weekend..

**Comment by ronoaldo** [comment]
This escalated quickly, closing with comments.

tl,dr: closing as wont-fix, please report to the Upstream repository by Wuzzy.

@mckaygerhard I understand your frustration but Minetest as a project is not longer one that I am involved with for several reasons. I just kept the code needed to run my server because we have a small but active player base at it. That said, I unfortunately cannot help you with this quest. As many open source projects, developer time is scarce and any contribution is welcome but I found myself having a hard time contributing to Minetest as well. Hope you have the patience to move this forward with the minetest development team/contributors. Wish you the best.

As a side note: be careful when calling out people names; this is usually not the best way to convince them to do something.
